const languages = {
  아희: 'aheui',
  엄준식: 'umm',
  Ada: 'ada',
  'Algol 68': 'a',
  APECODE: 'ape',
  Assembly: 'o',
  'Assembly (32bit)': 'o',
  'Assembly (64bit)': 'o',
  awk: 'awk',
  Bash: 'sh',
  bc: 'bc',
  Befunge: 'bf',
  Boo: 'boo',
  'Brainf**k': 'bf',
  C: 'c',
  'C#': 'cs',
  'C# 3.0 (Mono)': 'cs',
  'C# 6.0 (Mono)': 'cs',
  'C# 9.0 (.NET)': 'cs',
  'C++': 'cc',
  'C++11': 'cc',
  'C++11 (Clang)': 'cc',
  'C++14': 'cc',
  'C++14 (Clang)': 'cc',
  'C++17': 'cc',
  'C++17 (Clang)': 'cc',
  'C++20': 'cc',
  'C++20 (Clang)': 'cc',
  'C++98': 'cc',
  'C++98 (Clang)': 'cc',
  C11: 'c',
  'C11 (Clang)': 'c',
  C2x: 'c',
  'C2x (Clang)': 'c',
  C90: 'c',
  'C90 (Clang)': 'c',
  C99: 'c',
  'C99 (Clang)': 'c',
  Cobol: 'cob',
  Cobra: 'cobra',
  Coq: 'v',
  Crystal: 'cr',
  D: 'd',
  'D (LDC)': 'd',
  'F#': 'fs',
  'F# (.NET)': 'fs',
  'F# (Mono)': 'fs',
  Fortran: 'f',
  FreeBASIC: 'bas',
  Go: 'go',
  'Go (gccgo)': 'go',
  Golfscript: 'gs',
  Haskell: 'hs',
  Haxe: 'py',
  INTERCAL: 'i',
  Java: 'java',
  'Java 11': 'java',
  'Java 15': 'java',
  'Java 8': 'java',
  'Java 8 (OpenJDK)': 'java',
  Kotlin: 'kt',
  'Kotlin (JVM)': 'kt',
  'Kotlin (Native)': 'kt',
  LOLCODE: 'lol',
  Lua: 'lua',
  Minecraft: 'mca',
  Nemerle: 'n',
  Nimrod: 'nim',
  'node.js': 'js',
  'Objective-C': 'm',
  'Objective-C++': 'mm',
  OCaml: 'ml',
  Pascal: 'pas',
  Perl: 'pl',
  PHP: 'php',
  Pike: 'pike',
  PyPy: 'py',
  PyPy2: 'py',
  PyPy3: 'py',
  Python: 'py',
  'Python 2': 'py',
  'Python 3': 'py',
  Rhino: 'js',
  Ruby: 'rb',
  'Ruby 1.8': 'rb',
  'Ruby 1.9': 'rb',
  'Ruby 2': 'rb',
  Rust: 'rs',
  'Rust 2015': 'rs',
  'Rust 2018': 'rs',
  'Rust 2019': 'rs',
  'Rust 2021': 'rs',
  Scala: 'scala',
  Scheme: 'scm',
  sed: 'sed',
  Swift: 'swift',
  SystemVerilog: 'sv',
  Tcl: 'tcl',
  Text: 'txt',
  TypeScript: 'ts',
  'VB.NET 2.0 (Mono)': 'vb',
  'VB.NET 4.0 (Mono)': 'vb',
  'Visual Basic': 'vb',
  'Visual Basic (.NET)': 'vb',
  Whitespace: 'ws',
};

const darkTheme = {
  'cm-s-default': false,
  'cm-s-3024-day': false,
  'cm-s-3024-night': true,
  'cm-s-abcdef': true,
  'cm-s-ambiance': true,
  'cm-s-base16-dark': true,
  'cm-s-base16-light': false,
  'cm-s-bespin': true,
  'cm-s-blackboard': true,
  'cm-s-cobalt': true,
  'cm-s-colorforth': true,
  'cm-s-darcula': true,
  'cm-s-dracula': true,
  'cm-s-duotone-dark': true,
  'cm-s-duotone-light': false,
  'cm-s-eclipse': false,
  'cm-s-elegant': false,
  'cm-s-erlang-dark': true,
  'cm-s-gruvbox-dark': true,
  'cm-s-hopscotch': true,
  'cm-s-icecoder': true,
  'cm-s-idea': false,
  'cm-s-isotope': true,
  'cm-s-lesser-dark': true,
  'cm-s-liquibyte': true,
  'cm-s-lucario': true,
  'cm-s-material': true,
  'cm-s-mbo': true,
  'cm-s-mdn-like': false,
  'cm-s-midnight': true,
  'cm-s-monokai': true,
  'cm-s-neat': false,
  'cm-s-neo': false,
  'cm-s-night': true,
  'cm-s-nord': true,
  'cm-s-oceanic-next': true,
  'cm-s-panda-syntax': true,
  'cm-s-paraiso-dark': true,
  'cm-s-paraiso-light': false,
  'cm-s-pastel-on-dark': true,
  'cm-s-railscasts': true,
  'cm-s-rubyblue': true,
  'cm-s-seti': true,
  'cm-s-shadowfox': true,
  'cm-s-solarized dark': true,
  'cm-s-solarized light': false,
  'cm-s-the-matrix': true,
  'cm-s-tomorrow-night-bright': true,
  'cm-s-tomorrow-night-eighties': true,
  'cm-s-ttcn': false,
  'cm-s-twilight': true,
  'cm-s-vibrant-ink': true,
  'cm-s-xq-dark': true,
  'cm-s-xq-light': false,
  'cm-s-yeti': false,
  'cm-s-yonce': true,
  'cm-s-zenburn': true,
};
