export const BLOCK_TYPE = {
  CODE: "code",
  HEADING_LARGE: "heading_1",
  HEADING_MIDIUM: "heading_2",
  HEADING_SMALL: "heading_3",
  PARAGRAPH: "paragraph",
  TEXT: "text",
};

export const HEADING = {
  LARGE: "heading_1",
  MIDIUM: "heading_2",
  SMALL: "heading_3",
};

export const COLORS = {
  BLUE: "blue",
  BLUE_BACKGROUND: "blue_background",
  BROWN: "brown",
  BROWN_BACKGROUND: "brown_background",
  DEFAULT: "default",
  GRAY: "gray",
  GRAY_BACKGROUND: "gray_background",
  GREEN: "green",
  GREEN_BACKGROUND: "green_background",
  ORANGE: "orange",
  ORANGE_BACKGROUND: "orange_background",
  PINK: "pink",
  PINK_BACKGROUND: "pink_background",
  PURPLE: "purple",
  PURPLE_BACKGROUND: "purple_background",
  RED: "red",
  RED_BACKGROUND: "red_background",
  YELLOW: "yellow",
  YELLOW_BACKGROUND: "yellow_background",
};

export const CODE_LANGUAGES = {
  ABAP: "abap",
  ARDUINO: "arduino",
  BASH: "bash",
  BASIC: "basic",
  C: "c",
  CLOJURE: "clojure",
  COFFEESCRIPT: "coffeescript",
  CPP: "c++",
  C_SHARP: "c#",
  CSS: "css",
  DART: "dart",
  DIFF: "diff",
  DOCKER: "docker",
  ELIXIR: "elixir",
  ELM: "elm",
  ERLANG: "erlang",
  FLOW: "flow",
  FORTRAN: "fortran",
  F_SHARP: "f#",
  GHERKIN: "gherkin",
  GLSL: "glsl",
  GO: "go",
  GRAPHQL: "graphql",
  GROOVY: "groovy",
  HASKELL: "haskell",
  HTML: "html",
  JAVA: "java",
  JAVASCRIPT: "javascript",
  JSON: "json",
  JULIA: "julia",
  KOTLIN: "kotlin",
  LATEX: "latex",
  LESS: "less",
  LISP: "lisp",
  LIVESCRIPT: "livescript",
  LUA: "lua",
  MAKEFILE: "makefile",
  MARKDOWN: "markdown",
  MARKUP: "markup",
  MATLAB: "matlab",
  MERMAID: "mermaid",
  NIX: "nix",
  OBJECTIVE_C: "objective-c",
  OCAML: "ocaml",
  PASCAL: "pascal",
  PERL: "perl",
  PHP: "php",
  PLAIN_TEXT: "plain text",
  POWERSHELL: "powershell",
  PROLOG: "prolog",
  PROTOBUF: "protobuf",
  PYTHON: "python",
  R: "r",
  REASON: "reason",
  RUBY: "ruby",
  RUST: "rust",
  SASS: "sass",
  SCALA: "scala",
  SCHEME: "scheme",
  SCSS: "scss",
  SHELL: "shell",
  SQL: "sql",
  SWIFT: "swift",
  TYPESCRIPT: "typescript",
  VB_NET: "vb.net",
  VERILOG: "verilog",
  VHDL: "vhdl",
  VISUAL_BASIC: "visual basic",
  WEBASSEMBLY: "webassembly",
  XML: "xml",
  YAML: "yaml",
  JAVA_C_CPP_C_SHARP: "java/c/c++/c#",
};

export const LANGUAGES = {
  "아희": "plain text",
  "엄준식": "plain text",
  "Ada": "plain text",
  "Algol 68": "plain text",
  "APECODE": "plain text",
  "Assembly": "plain text",
  "Assembly (32bit)": "plain text",
  "Assembly (64bit)": "plain text",
  "awk": "plain text",
  "Bash": "bash",
  "bc": "plain text",
  "Befunge": "plain text",
  "Boo": "plain text",
  "Brainf**k": "plain text",
  "C": "c",
  "C#": "c#",
  "C# 3.0 (Mono)": "c#",
  "C# 6.0 (Mono)": "c#",
  "C# 9.0 (.NET)": "c#",
  "C++": "c++",
  "C++11": "c++",
  "C++11 (Clang)": "c++",
  "C++14": "c++",
  "C++14 (Clang)": "c++",
  "C++17": "c++",
  "C++17 (Clang)": "c++",
  "C++20": "c++",
  "C++20 (Clang)": "c++",
  "C++98": "c++",
  "C++98 (Clang)": "c++",
  "C11": "c",
  "C11 (Clang)": "c",
  "C2x": "c",
  "C2x (Clang)": "c",
  "C90": "c",
  "C90 (Clang)": "c",
  "C99": "c",
  "C99 (Clang)": "c",
  "Cobol": "plain text",
  "Cobra": "plain text",
  "Coq": "plain text",
  "Crystal": "plain text",
  "D": "plain text",
  "D (LDC)": "plain text",
  "F#": "f#",
  "F# (.NET)": "f#",
  "F# (Mono)": "f#",
  "Fortran": "fortran",
  "FreeBASIC": "basic",
  "Go": "go",
  "Go (gccgo)": "go",
  "Golfscript": "plain text",
  "Haskell": "haskell",
  "Haxe": "plain text",
  "INTERCAL": "plain text",
  "Java": "java",
  "Java 11": "java",
  "Java 15": "java",
  "Java 8": "java",
  "Java 8 (OpenJDK)": "java",
  "Kotlin": "kotlin",
  "Kotlin (JVM)": "kotlin",
  "Kotlin (Native)": "kotlin",
  "LOLCODE": "plain text",
  "Lua": "lua",
  "Minecraft": "plain text",
  "Nemerle": "plain text",
  "Nimrod": "plain text",
  "node.js": "javascript",
  "Objective-C": "objective-c",
  "Objective-C++": "objective-c",
  "OCaml": "ocaml",
  "Pascal": "pascal",
  "Perl": "perl",
  "PHP": "php",
  "Pike": "plain text",
  "PyPy": "python",
  "PyPy2": "python",
  "PyPy3": "python",
  "Python": "python",
  "Python 2": "python",
  "Python 3": "python",
  "Rhino": "plain text",
  "Ruby": "ruby",
  "Ruby 1.8": "ruby",
  "Ruby 1.9": "ruby",
  "Ruby 2": "ruby",
  "Rust": "rust",
  "Rust 2015": "rust",
  "Rust 2018": "rust",
  "Rust 2019": "rust",
  "Rust 2021": "rust",
  "Scala": "scala",
  "Scheme": "scheme",
  "sed": "plain text",
  "Swift": "swift",
  "SystemVerilog": "plain text",
  "Tcl": "plain text",
  "Text": "plain text",
  "TypeScript": "typescript",
  "VB.NET 2.0 (Mono)": "visual basic",
  "VB.NET 4.0 (Mono)": "visual basic",
  "Visual Basic": "visual basic",
  "Visual Basic (.NET)": "plain text",
  "Whitespace": "plain text",
};
